"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostStatusResponse = exports.PagedStatusItemResponse = exports.UnfollowResponse = exports.FollowResponse = exports.IsFollowerResponse = exports.GetCountResponse = exports.PagedUserItemResponse = exports.GetUserResponse = exports.LogoutResponse = exports.LoginResponse = exports.RegisterResponse = exports.PostStatusRequest = exports.PagedStatusItemRequest = exports.UnfollowRequest = exports.FollowRequest = exports.IsFollowerRequest = exports.GetCountRequest = exports.PagedUserItemRequest = exports.GetUserRequest = exports.LogoutRequest = exports.LoginRequest = exports.RegisterRequest = exports.FakeData = exports.AuthToken = exports.User = exports.Status = exports.Type = exports.PostSegment = exports.Follow = void 0;
// Domain
var Follow_1 = require("./model/domain/Follow");
Object.defineProperty(exports, "Follow", { enumerable: true, get: function () { return Follow_1.Follow; } });
var PostSegment_1 = require("./model/domain/PostSegment");
Object.defineProperty(exports, "PostSegment", { enumerable: true, get: function () { return PostSegment_1.PostSegment; } });
Object.defineProperty(exports, "Type", { enumerable: true, get: function () { return PostSegment_1.Type; } });
var Status_1 = require("./model/domain/Status");
Object.defineProperty(exports, "Status", { enumerable: true, get: function () { return Status_1.Status; } });
var User_1 = require("./model/domain/User");
Object.defineProperty(exports, "User", { enumerable: true, get: function () { return User_1.User; } });
var AuthToken_1 = require("./model/domain/AuthToken");
Object.defineProperty(exports, "AuthToken", { enumerable: true, get: function () { return AuthToken_1.AuthToken; } });
// Util
var FakeData_1 = require("./util/FakeData");
Object.defineProperty(exports, "FakeData", { enumerable: true, get: function () { return FakeData_1.FakeData; } });
// Requests
var RegisterRequest_1 = require("./request/RegisterRequest");
Object.defineProperty(exports, "RegisterRequest", { enumerable: true, get: function () { return RegisterRequest_1.RegisterRequest; } });
var LoginRequest_1 = require("./request/LoginRequest");
Object.defineProperty(exports, "LoginRequest", { enumerable: true, get: function () { return LoginRequest_1.LoginRequest; } });
var LogoutRequest_1 = require("./request/LogoutRequest");
Object.defineProperty(exports, "LogoutRequest", { enumerable: true, get: function () { return LogoutRequest_1.LogoutRequest; } });
var GetUserRequest_1 = require("./request/GetUserRequest");
Object.defineProperty(exports, "GetUserRequest", { enumerable: true, get: function () { return GetUserRequest_1.GetUserRequest; } });
var PagedUserItemRequest_1 = require("./request/PagedUserItemRequest");
Object.defineProperty(exports, "PagedUserItemRequest", { enumerable: true, get: function () { return PagedUserItemRequest_1.PagedUserItemRequest; } });
var GetCountRequest_1 = require("./request/GetCountRequest");
Object.defineProperty(exports, "GetCountRequest", { enumerable: true, get: function () { return GetCountRequest_1.GetCountRequest; } });
var IsFollowerRequest_1 = require("./request/IsFollowerRequest");
Object.defineProperty(exports, "IsFollowerRequest", { enumerable: true, get: function () { return IsFollowerRequest_1.IsFollowerRequest; } });
var FollowRequest_1 = require("./request/FollowRequest");
Object.defineProperty(exports, "FollowRequest", { enumerable: true, get: function () { return FollowRequest_1.FollowRequest; } });
var UnfollowRequest_1 = require("./request/UnfollowRequest");
Object.defineProperty(exports, "UnfollowRequest", { enumerable: true, get: function () { return UnfollowRequest_1.UnfollowRequest; } });
var PagedStatusItemRequest_1 = require("./request/PagedStatusItemRequest");
Object.defineProperty(exports, "PagedStatusItemRequest", { enumerable: true, get: function () { return PagedStatusItemRequest_1.PagedStatusItemRequest; } });
var PostStatusRequest_1 = require("./request/PostStatusRequest");
Object.defineProperty(exports, "PostStatusRequest", { enumerable: true, get: function () { return PostStatusRequest_1.PostStatusRequest; } });
// Responses
var RegisterResponse_1 = require("./response/RegisterResponse");
Object.defineProperty(exports, "RegisterResponse", { enumerable: true, get: function () { return RegisterResponse_1.RegisterResponse; } });
var LoginResponse_1 = require("./response/LoginResponse");
Object.defineProperty(exports, "LoginResponse", { enumerable: true, get: function () { return LoginResponse_1.LoginResponse; } });
var LogoutResponse_1 = require("./response/LogoutResponse");
Object.defineProperty(exports, "LogoutResponse", { enumerable: true, get: function () { return LogoutResponse_1.LogoutResponse; } });
var GetUserResponse_1 = require("./response/GetUserResponse");
Object.defineProperty(exports, "GetUserResponse", { enumerable: true, get: function () { return GetUserResponse_1.GetUserResponse; } });
var PagedUserItemResponse_1 = require("./response/PagedUserItemResponse");
Object.defineProperty(exports, "PagedUserItemResponse", { enumerable: true, get: function () { return PagedUserItemResponse_1.PagedUserItemResponse; } });
var GetCountResponse_1 = require("./response/GetCountResponse");
Object.defineProperty(exports, "GetCountResponse", { enumerable: true, get: function () { return GetCountResponse_1.GetCountResponse; } });
var IsFollowerResponse_1 = require("./response/IsFollowerResponse");
Object.defineProperty(exports, "IsFollowerResponse", { enumerable: true, get: function () { return IsFollowerResponse_1.IsFollowerResponse; } });
var FollowResponse_1 = require("./response/FollowResponse");
Object.defineProperty(exports, "FollowResponse", { enumerable: true, get: function () { return FollowResponse_1.FollowResponse; } });
var UnfollowResponse_1 = require("./response/UnfollowResponse");
Object.defineProperty(exports, "UnfollowResponse", { enumerable: true, get: function () { return UnfollowResponse_1.UnfollowResponse; } });
var PagedStatusItemResponse_1 = require("./response/PagedStatusItemResponse");
Object.defineProperty(exports, "PagedStatusItemResponse", { enumerable: true, get: function () { return PagedStatusItemResponse_1.PagedStatusItemResponse; } });
var PostStatusResponse_1 = require("./response/PostStatusResponse");
Object.defineProperty(exports, "PostStatusResponse", { enumerable: true, get: function () { return PostStatusResponse_1.PostStatusResponse; } });
